### ISSUE TITLE
唉，我缺的是学习资料吗？我缺的是学习的动力啊。怎么能白嫖到学习的动力？

### ISSUE THREAD

**Issue by daijie1223** [ben1234560/AiLearning-Theory-Applying#1]

**Comment by ben1234560** [comment]
涨钱算动力吗。
1. 公司招人，交付to金融方向，自研智能运维。
2. 竞赛找人组队，个人战绩：solo前10（1000+队伍/当前），kaggle soloTop2%（历史），带队冲牌子等，保铜银冲金。
3. 重点：以上均是**白嫖项目**。感兴趣发我邮箱：909336740@qq.com。
